baseURL = "https://selavy.github.io/"
languageCode = "en-us"
title = "c'est la vie"
theme = "kiera"
# theme = "tale"
canonifyurls = true

# Kiera Theme Configuration
pygmentsCodeFences = true
[author]
    name = "Peter Lesslie"       #Author name
    github = "selavy"     #Github username
#    gitlab = ""     #Gitlab username
#    linkedin = ""   #LinkedIn username
#    facebook = ""   #Facebook username
#    twitter = ""    #Twitter username
#    instagram = ""  #Instagram username

#[params]
#    tagline = "the tagline for this website"
